# Domains to be removed from the doh and doh-vpn-proxy-bypass list.
# Apple Intelligence, Siri
# https://github.com/hagezi/dns-blocklists/issues/5737#issuecomment-2771431741
# CNAME for apple-relay.apple.com
# https://github.com/hagezi/dns-blocklists/issues/6090
# CNAME
# Not Apple Private Relay related
# https://github.com/hagezi/dns-blocklists/issues/6422

DOMAIN-SUFFIX,brave.com,REJECT
DOMAIN-SUFFIX,cdn77.org,REJECT
DOMAIN-SUFFIX,cloudns.net,REJECT
DOMAIN-SUFFIX,discord.com,REJECT
DOMAIN-SUFFIX,f-secure.com,REJECT
DOMAIN-SUFFIX,fly.io,REJECT
DOMAIN-SUFFIX,fortinet.com,REJECT
DOMAIN-SUFFIX,fortinet.net,REJECT
DOMAIN-SUFFIX,fortiwebcloud.net,REJECT
DOMAIN-SUFFIX,iot-dns.com,REJECT
DOMAIN-SUFFIX,myfritz.net,REJECT
DOMAIN-SUFFIX,namecheap.com,REJECT
DOMAIN-SUFFIX,safebrowsing.apple,REJECT
DOMAIN-SUFFIX,salesforceliveagent.com,REJECT
DOMAIN-SUFFIX,yahoodns.net,REJECT
DOMAIN-SUFFIX,api.w.org,REJECT
DOMAIN-SUFFIX,apple-dns.net,REJECT
DOMAIN-SUFFIX,cdn.onesignal.com,REJECT
DOMAIN-SUFFIX,checkpoint.com,REJECT
DOMAIN-SUFFIX,clarity.ms,REJECT
DOMAIN-SUFFIX,dnschecker.org,REJECT
DOMAIN-SUFFIX,easydns.com,REJECT
DOMAIN-SUFFIX,incognet.io,REJECT
DOMAIN-SUFFIX,mathnodes.com,REJECT
DOMAIN-SUFFIX,noip.com,REJECT
DOMAIN-SUFFIX,norton.com,REJECT
DOMAIN-SUFFIX,ogp.me,REJECT
DOMAIN-SUFFIX,openvpn.net,REJECT
DOMAIN-SUFFIX,opera-api.com,REJECT
DOMAIN-SUFFIX,opera-api2.com,REJECT
DOMAIN-SUFFIX,opera-mini.net,REJECT
DOMAIN-SUFFIX,opera.com,REJECT
DOMAIN-SUFFIX,opera.software,REJECT
DOMAIN-SUFFIX,paddle.com,REJECT
DOMAIN-SUFFIX,public-dns.info,REJECT
DOMAIN-SUFFIX,safebrowsing.google.com,REJECT
DOMAIN-SUFFIX,safebrowsing.googleapis.com,REJECT
DOMAIN-SUFFIX,savefrom.net,REJECT
DOMAIN-SUFFIX,use-application-dns.net,REJECT
DOMAIN-SUFFIX,vpn.surf,REJECT
DOMAIN-SUFFIX,wireguard.com,REJECT
DOMAIN-SUFFIX,xeovo.com,REJECT
DOMAIN-SUFFIX,youtube.com,REJECT
DOMAIN-SUFFIX,apple-relay.akamaized.net,REJECT
DOMAIN-SUFFIX,apple-relay.apple.com,REJECT
DOMAIN-SUFFIX,apple-relay.cloudflare.com,REJECT
DOMAIN-SUFFIX,apple-relay.fastly-edge.com,REJECT
DOMAIN-SUFFIX,apple-relay.mask.apple-dns.net,REJECT
DOMAIN-SUFFIX,mask-api.icloud.com,REJECT
DOMAIN-SUFFIX,mask-api.fe2.apple-dns.net,REJECT
DOMAIN-SUFFIX,mask.apple-dns.net,REJECT
DOMAIN-SUFFIX,mask-boot.icloud.com,REJECT
DOMAIN-SUFFIX,mask-canary.icloud.com,REJECT
DOMAIN-SUFFIX,staging.apple-carry-relay.cloudflare.com,REJECT
