# Domains to be removed from the hoster list.

DOMAIN-SUFFIX,comcast.net,REJECT
DOMAIN-SUFFIX,dkimwl.org,REJECT
DOMAIN-SUFFIX,dynadot.com,REJECT
DOMAIN-SUFFIX,elementor.com,REJECT
DOMAIN-SUFFIX,eu.org,REJECT
DOMAIN-SUFFIX,google.com,REJECT
DOMAIN-SUFFIX,googleblog.com,REJECT
DOMAIN-SUFFIX,googleusercontent.com,REJECT
DOMAIN-SUFFIX,heliohost.org,REJECT
DOMAIN-SUFFIX,livejournal.com,REJECT
DOMAIN-SUFFIX,mozilla.org,REJECT
DOMAIN-SUFFIX,pixnet.net,REJECT
DOMAIN-SUFFIX,tistory.com,REJECT
DOMAIN-SUFFIX,tumblr.com,REJECT
DOMAIN-SUFFIX,windows.net,REJECT
DOMAIN-SUFFIX,wordpress.com,REJECT
DOMAIN-SUFFIX,wp.com,REJECT
DOMAIN-SUFFIX,wpengine.com,REJECT
DOMAIN-SUFFIX,wpenginepowered.com,REJECT
DOMAIN-SUFFIX,wpeproxy.com,REJECT
DOMAIN-SUFFIX,0hi.me,REJECT
DOMAIN-SUFFIX,2chblog.jp,REJECT
DOMAIN-SUFFIX,amazon.se,REJECT
DOMAIN-SUFFIX,amplifyapp.com,REJECT
DOMAIN-SUFFIX,bazaarvoice.com,REJECT
DOMAIN-SUFFIX,blog.csdn.net,REJECT
DOMAIN-SUFFIX,blog.jp,REJECT
DOMAIN-SUFFIX,bloggeek.jp,REJECT
DOMAIN-SUFFIX,blogism.jp,REJECT
DOMAIN-SUFFIX,blogo.jp,REJECT
DOMAIN-SUFFIX,blogs.es,REJECT
DOMAIN-SUFFIX,blogstation.jp,REJECT
DOMAIN-SUFFIX,blogto.jp,REJECT
DOMAIN-SUFFIX,cafeblog.jp,REJECT
DOMAIN-SUFFIX,cnblogs.com,REJECT
DOMAIN-SUFFIX,corpblog.jp,REJECT
DOMAIN-SUFFIX,diary.to,REJECT
DOMAIN-SUFFIX,doorblog.jp,REJECT
DOMAIN-SUFFIX,dreamlog.jp,REJECT
DOMAIN-SUFFIX,editmysite.com,REJECT
DOMAIN-SUFFIX,gger.jp,REJECT
DOMAIN-SUFFIX,golog.jp,REJECT
DOMAIN-SUFFIX,hateblo.jp,REJECT
DOMAIN-SUFFIX,hatena.ne.jp,REJECT
DOMAIN-SUFFIX,hatenablog.com,REJECT
DOMAIN-SUFFIX,hatenablog.jp,REJECT
DOMAIN-SUFFIX,hatenadiary.com,REJECT
DOMAIN-SUFFIX,hatenadiary.jp,REJECT
DOMAIN-SUFFIX,hatenadiary.org,REJECT
DOMAIN-SUFFIX,hosteurope.de,REJECT
DOMAIN-SUFFIX,karneval.cz,REJECT
DOMAIN-SUFFIX,ldblog.jp,REJECT
DOMAIN-SUFFIX,liblo.jp,REJECT
DOMAIN-SUFFIX,livedoor.biz,REJECT
DOMAIN-SUFFIX,multiscreensite.com,REJECT
DOMAIN-SUFFIX,myjournal.jp,REJECT
DOMAIN-SUFFIX,mynikki.jp,REJECT
DOMAIN-SUFFIX,officeblog.jp,REJECT
DOMAIN-SUFFIX,officialblog.jp,REJECT
DOMAIN-SUFFIX,one.com,REJECT
DOMAIN-SUFFIX,onrender.com,REJECT
DOMAIN-SUFFIX,pantheonsite.io,REJECT
DOMAIN-SUFFIX,pcdn.co,REJECT
DOMAIN-SUFFIX,php-friends.de,REJECT
DOMAIN-SUFFIX,publog.jp,REJECT
DOMAIN-SUFFIX,revk.uk,REJECT
DOMAIN-SUFFIX,st-hatena.com,REJECT
DOMAIN-SUFFIX,storeblog.jp,REJECT
DOMAIN-SUFFIX,teamblog.jp,REJECT
DOMAIN-SUFFIX,techblog.jp,REJECT
DOMAIN-SUFFIX,tele2.se,REJECT
DOMAIN-SUFFIX,tilda.cc,REJECT
DOMAIN-SUFFIX,tilda.es,REJECT
DOMAIN-SUFFIX,tildacdn.com,REJECT
DOMAIN-SUFFIX,typepad.com,REJECT
DOMAIN-SUFFIX,webflow.com,REJECT
DOMAIN-SUFFIX,weblog.to,REJECT
DOMAIN-SUFFIX,wix.com,REJECT
DOMAIN-SUFFIX,x10hosting.com,REJECT
DOMAIN-SUFFIX,xxxblog.jp,REJECT
DOMAIN-SUFFIX,youblog.jp,REJECT
