# Unblocking for relaxed and balanced lists (non-aggressive) only.
# https://github.com/hagezi/dns-blocklists/issues/4941
# https://github.com/hagezi/dns-blocklists/issues/6262
# https://github.com/hagezi/dns-blocklists/issues/6075
# https://github.com/hagezi/dns-blocklists/issues/5625
# Newsletter (un)subscribe/links (Quarks and other german sites)
# Referral
# Office365 - Save documents to the cloud
# https://learn.microsoft.com/en-us/windows/privacy/manage-windows-11-endpoints
# Videos on https://www.tv8.it/streaming
# https://github.com/hagezi/dns-blocklists/issues/2754
# https://github.com/hagezi/dns-blocklists/issues/2757
# https://github.com/hagezi/dns-blocklists/issues/2437#issuecomment-2053875051
# https://github.com/hagezi/dns-blocklists/issues/2582
# Unsubscribe from newsletters (e.g. RND)
# https://github.com/hagezi/dns-blocklists/issues/2260
# Possible fix for the data octopus Tiktok:
#  - You can't follow anyone
#  - Random content doesn't load
#  - Profiles remains empty
#  - The app shows a network error
#  - The same videos are often suggested
# These errors are not reproducible and occur very rarely.
# This Tiktoktupus app is the absolute privacy plague!
# The domains will remain blocked in the native and aggressive lists for the time being.
# https://github.com/hagezi/dns-blocklists/issues/1768
# https://github.com/hagezi/dns-blocklists/issues/4587

DOMAIN-SUFFIX,cdn.convertbox.com,REJECT
DOMAIN-SUFFIX,app.convertbox.com,REJECT
DOMAIN-SUFFIX,remote-data.asnapieu.com,REJECT
DOMAIN-SUFFIX,raka.bing.com,REJECT
DOMAIN-SUFFIX,delivers.dtignite.com,REJECT
DOMAIN-SUFFIX,api.cleverpush.com,REJECT
DOMAIN-SUFFIX,static.cleverpush.com,REJECT
DOMAIN-SUFFIX,api-eu.cleverpush.com,REJECT
DOMAIN-SUFFIX,static-eu.cleverpush.com,REJECT
DOMAIN-SUFFIX,engagements.appsflyer.com,REJECT
DOMAIN-SUFFIX,ecs.nel.measure.office.net,REJECT
DOMAIN-SUFFIX,cdn.speedcurve.com,REJECT
DOMAIN-SUFFIX,telemetry.banuba.cloud,REJECT
DOMAIN-SUFFIX,stats.sdk.banuba.net,REJECT
DOMAIN-SUFFIX,sdk-01.moengage.com,REJECT
DOMAIN-SUFFIX,a0.app.xiaomi.com,REJECT
DOMAIN-SUFFIX,karavel.112.2o7.net,REJECT
DOMAIN-SUFFIX,api.pushwoosh.com,REJECT
DOMAIN-SUFFIX,webhook.logentries.com,REJECT
DOMAIN-SUFFIX,micro.rubiconproject.com,REJECT
DOMAIN-SUFFIX,digicertwc.rubiconproject.com.edgekey.net,REJECT
DOMAIN-SUFFIX,e8960.e2.akamaiedge.net,REJECT
