# Domains to be removed from the anti piracy list.

DOMAIN-SUFFIX,abload.de,REJECT
DOMAIN-SUFFIX,adultfriendfinder.com,REJECT
DOMAIN-SUFFIX,ahstatic.com,REJECT
DOMAIN-SUFFIX,archive.org,REJECT
DOMAIN-SUFFIX,bgp.he.net,REJECT
DOMAIN-SUFFIX,bttrack.com,REJECT
DOMAIN-SUFFIX,catbox.moe,REJECT
DOMAIN-SUFFIX,dazn.com,REJECT
DOMAIN-SUFFIX,dex.email,REJECT
DOMAIN-SUFFIX,discord.com,REJECT
DOMAIN-SUFFIX,discord.gg,REJECT
DOMAIN-SUFFIX,dropboxusercontent.com,REJECT
DOMAIN-SUFFIX,fliphtml5.com,REJECT
DOMAIN-SUFFIX,foxsports.com,REJECT
DOMAIN-SUFFIX,gamepressure.com,REJECT
DOMAIN-SUFFIX,github.com,REJECT
DOMAIN-SUFFIX,github.io,REJECT
DOMAIN-SUFFIX,google.com,REJECT
DOMAIN-SUFFIX,gov,REJECT
DOMAIN-SUFFIX,grc.com,REJECT
DOMAIN-SUFFIX,greasyfork.org,REJECT
DOMAIN-SUFFIX,gutenberg.org,REJECT
DOMAIN-SUFFIX,hulu.com,REJECT
DOMAIN-SUFFIX,ibb.co,REJECT
DOMAIN-SUFFIX,ibiblio.org,REJECT
DOMAIN-SUFFIX,imgur.com,REJECT
DOMAIN-SUFFIX,infodrones.it,REJECT
DOMAIN-SUFFIX,jio.com,REJECT
DOMAIN-SUFFIX,kinguin.net,REJECT
DOMAIN-SUFFIX,live.com,REJECT
DOMAIN-SUFFIX,llnwd.net,REJECT
DOMAIN-SUFFIX,mesh.com,REJECT
DOMAIN-SUFFIX,moviefone.com,REJECT
DOMAIN-SUFFIX,mpg.de,REJECT
DOMAIN-SUFFIX,netbsd.org,REJECT
DOMAIN-SUFFIX,netzwelt.de,REJECT
DOMAIN-SUFFIX,pangle.io,REJECT
DOMAIN-SUFFIX,pastebin.com,REJECT
DOMAIN-SUFFIX,playstation.net,REJECT
DOMAIN-SUFFIX,redd.it,REJECT
DOMAIN-SUFFIX,reddit.com,REJECT
DOMAIN-SUFFIX,rentry.co,REJECT
DOMAIN-SUFFIX,sandisk.com,REJECT
DOMAIN-SUFFIX,schema.org,REJECT
DOMAIN-SUFFIX,sportdeutschland.tv,REJECT
DOMAIN-SUFFIX,srf.ch,REJECT
DOMAIN-SUFFIX,steampowered.com,REJECT
DOMAIN-SUFFIX,stremio.com,REJECT
DOMAIN-SUFFIX,surfshark.com,REJECT
DOMAIN-SUFFIX,t.me,REJECT
DOMAIN-SUFFIX,telegram.dog,REJECT
DOMAIN-SUFFIX,telegram.me,REJECT
DOMAIN-SUFFIX,yandex.ru,REJECT
DOMAIN-SUFFIX,zattoo.com,REJECT
DOMAIN-SUFFIX,zee5.com,REJECT
DOMAIN-SUFFIX,activated.win,REJECT
DOMAIN-SUFFIX,alternativeto.net,REJECT
DOMAIN-SUFFIX,brew.sh,REJECT
DOMAIN-SUFFIX,bttracker.debian.org,REJECT
DOMAIN-SUFFIX,european-alternatives.eu,REJECT
DOMAIN-SUFFIX,f1-dash.com,REJECT
DOMAIN-SUFFIX,heroicgameslauncher.com,REJECT
DOMAIN-SUFFIX,hoopladigital.com,REJECT
DOMAIN-SUFFIX,jiocinema.com,REJECT
DOMAIN-SUFFIX,laola1.at,REJECT
DOMAIN-SUFFIX,macmenubar.com,REJECT
DOMAIN-SUFFIX,mxplayer.in,REJECT
DOMAIN-SUFFIX,neocities.org,REJECT
DOMAIN-SUFFIX,neolinks.cfd,REJECT
DOMAIN-SUFFIX,pirateparty.gr,REJECT
DOMAIN-SUFFIX,playary.com,REJECT
DOMAIN-SUFFIX,rabbitholebd.com,REJECT
DOMAIN-SUFFIX,saltwood.top,REJECT
DOMAIN-SUFFIX,sexuria.net,REJECT
DOMAIN-SUFFIX,sindresorhus.com,REJECT
DOMAIN-SUFFIX,studyflix.de,REJECT
DOMAIN-SUFFIX,tracker.samplicio.us,REJECT
DOMAIN-SUFFIX,tracker.unbxdapi.com,REJECT
DOMAIN-SUFFIX,yuptracker.gaijinent.com,REJECT
