# Domains to be removed from the nsfw list.

DOMAIN-SUFFIX,archive.org,REJECT
DOMAIN-SUFFIX,codeberg.org,REJECT
DOMAIN-SUFFIX,discord.com,REJECT
DOMAIN-SUFFIX,discord.gg,REJECT
DOMAIN-SUFFIX,disroot.org,REJECT
DOMAIN-SUFFIX,fmhy.net,REJECT
DOMAIN-SUFFIX,github.com,REJECT
DOMAIN-SUFFIX,github.io,REJECT
DOMAIN-SUFFIX,gitlab.com,REJECT
DOMAIN-SUFFIX,google.com,REJECT
DOMAIN-SUFFIX,greasyfork.org,REJECT
DOMAIN-SUFFIX,imagelabs.net,REJECT
DOMAIN-SUFFIX,netflix.net,REJECT
DOMAIN-SUFFIX,nflxvideo.net,REJECT
DOMAIN-SUFFIX,pastebin.com,REJECT
DOMAIN-SUFFIX,redd.it,REJECT
DOMAIN-SUFFIX,reddit.com,REJECT
DOMAIN-SUFFIX,rentry.co,REJECT
DOMAIN-SUFFIX,rsc.cdn77.org,REJECT
DOMAIN-SUFFIX,t.me,REJECT
DOMAIN-SUFFIX,benefitsatwork.be,REJECT
DOMAIN-SUFFIX,catflix.su,REJECT
DOMAIN-SUFFIX,channel5.com,REJECT
DOMAIN-SUFFIX,do7go.com,REJECT
DOMAIN-SUFFIX,dooodster.com,REJECT
DOMAIN-SUFFIX,invisionzone.com,REJECT
DOMAIN-SUFFIX,jeuxvideo.com,REJECT
DOMAIN-SUFFIX,keenetic.name,REJECT
DOMAIN-SUFFIX,marthabeth.com,REJECT
DOMAIN-SUFFIX,nebenan.de,REJECT
DOMAIN-SUFFIX,sotwe.com,REJECT
DOMAIN-SUFFIX,subtitlecat.com,REJECT
DOMAIN-SUFFIX,fgov.be,REJECT
