# Domains to be removed from the tif and tif medium/mini list.
# https://github.com/hagezi/dns-blocklists/issues/6794
# Dedicated to dnscheck.tools RRSIG checks
# https://github.com/hagezi/dns-blocklists/issues/5303
# https://github.com/hagezi/dns-blocklists/issues/5046
# https://github.com/hagezi/dns-blocklists/issues/3385
# https://github.com/hagezi/dns-blocklists/issues/2436
# Not malicious, analytics, moved to normal lists
# https://github.com/hagezi/dns-blocklists/issues/4727

DOMAIN-SUFFIX,cdn.pawns.app,REJECT
DOMAIN-SUFFIX,analytics.community-scripts.org,REJECT
DOMAIN-SUFFIX,null-addr.net,REJECT
DOMAIN-SUFFIX,ak-is2.net,REJECT
DOMAIN-SUFFIX,pushub.xs.ak-is2.net,REJECT
DOMAIN-SUFFIX,usw-tencentclb.net,REJECT
DOMAIN-SUFFIX,trk.newpowerads.com,REJECT
DOMAIN-SUFFIX,trk.thinkbigmediax.com,REJECT
DOMAIN-SUFFIX,crash.syncthing.net,REJECT
DOMAIN-SUFFIX,keen.com,REJECT
DOMAIN-SUFFIX,analytics.arpae.it,REJECT
DOMAIN-SUFFIX,jjpool.fr,REJECT
DOMAIN-SUFFIX,xiaomi.com,REJECT
DOMAIN-SUFFIX,xiaomi.net,REJECT
DOMAIN-SUFFIX,miui.com,REJECT
DOMAIN-SUFFIX,mi.com,REJECT
DOMAIN-SUFFIX,advertising.com,REJECT
