# Domains to be removed from the dyndns list.

DOMAIN-SUFFIX,cloudns.net,REJECT
DOMAIN-SUFFIX,myfritz.link,REJECT
DOMAIN-SUFFIX,myfritz.net,REJECT
DOMAIN-SUFFIX,strato.com,REJECT
DOMAIN-SUFFIX,synology.me,REJECT
DOMAIN-SUFFIX,pp.ua,REJECT
DOMAIN-SUFFIX,xsph.ru,REJECT
