# Domains to be removed from the nosafesearch list.

DOMAIN-SUFFIX,brave.com,REJECT
DOMAIN-SUFFIX,ecosia.org,REJECT
DOMAIN-SUFFIX,kagi.com,REJECT
DOMAIN-SUFFIX,perfectpixel.de,REJECT
DOMAIN-SUFFIX,perplexity.ai,REJECT
DOMAIN-SUFFIX,startpage.com,REJECT
DOMAIN-SUFFIX,swisscows.com,REJECT
DOMAIN-SUFFIX,yahoo.com,REJECT
DOMAIN-SUFFIX,zzls.xyz,REJECT
DOMAIN-SUFFIX,spot.ecloud.global,REJECT
DOMAIN-SUFFIX,spot.murena.io,REJECT
