# Unblocking for relaxed lists only
# https://github.com/hagezi/dns-blocklists/issues/6893
# https://github.com/hagezi/dns-blocklists/issues/6811
# https://github.com/hagezi/dns-blocklists/issues/5943
# https://github.com/hagezi/dns-blocklists/issues/5223
# https://github.com/hagezi/dns-blocklists/issues/4948
# https://github.com/hagezi/dns-blocklists/issues/4928
# Floods the dns with requests when blocked, possible battery drain on mobile devices.
# If not blocked, 1-2 requests are made per day.
# Used for de-identified telemetry (DIT, anonymized telemetry) to collect integrity, reliability and performance data.
# https://faq.whatsapp.com/538382354780857/
# https://github.com/hagezi/dns-blocklists/issues/4245
# Adblock detection iOS app derstandard.at
# https://github.com/hagezi/dns-blocklists/issues/2229
# https://github.com/hagezi/dns-blocklists/issues/1183
# War Gaming Tile
# atresplayer.com videos on live channels
# see: https://github.com/hagezi/dns-blocklists/issues/6662
### 7db96.v.fwmrm.net
# Breaks on-demand videos of Mediaset programs from smart TVs
# Because it is a disguised, popular CNAME tracker, it is not unblocked in the aggressive lists.

DOMAIN-SUFFIX,api.mantis-intelligence.com,REJECT
DOMAIN-SUFFIX,514001643.collect.igodigital.com,REJECT
DOMAIN-SUFFIX,variations.brave.com,REJECT
DOMAIN-SUFFIX,variations.bravesoftware.com,REJECT
DOMAIN-SUFFIX,smetrics.miles-and-more.com,REJECT
DOMAIN-SUFFIX,miles-and-more.com.data.adobedc.net,REJECT
DOMAIN-SUFFIX,ws.batch.com,REJECT
DOMAIN-SUFFIX,siteintercept.qualtrics.com,REJECT
DOMAIN-SUFFIX,siteintercept.qualtrics.com.cdn.cloudflare.net,REJECT
DOMAIN-SUFFIX,api.segment.io,REJECT
DOMAIN-SUFFIX,dit.whatsapp.net,REJECT
DOMAIN-SUFFIX,callrail.com,REJECT
DOMAIN-SUFFIX,data-dda7d24eb2.derstandard.at,REJECT
DOMAIN-SUFFIX,at-w-atderstand-relay.iocnt.net,REJECT
DOMAIN-SUFFIX,relay-client-c03.iocnt.net,REJECT
DOMAIN-SUFFIX,imagesrv.adition.com,REJECT
DOMAIN-SUFFIX,px.staticfiles.at,REJECT
DOMAIN-SUFFIX,ad3.adfarm1.adition.com,REJECT
DOMAIN-SUFFIX,ad.71i.de,REJECT
DOMAIN-SUFFIX,data.sportdeutschland.tv,REJECT
DOMAIN-SUFFIX,track.wargaming-aff.com,REJECT
DOMAIN-SUFFIX,www3.doubleclick.net,REJECT
DOMAIN-SUFFIX,mediasetitalia01.wt-eu02.net,REJECT
