# Domains to be added to the dyndns list.

DOMAIN-SUFFIX,any64.de,REJECT
DOMAIN-SUFFIX,api64.de,REJECT
DOMAIN-SUFFIX,cloudns.be,REJECT
DOMAIN-SUFFIX,cloudns.biz,REJECT
DOMAIN-SUFFIX,cloudns.ch,REJECT
DOMAIN-SUFFIX,dns64.de,REJECT
DOMAIN-SUFFIX,dynamic-dns.net,REJECT
DOMAIN-SUFFIX,dyndns64.de,REJECT
DOMAIN-SUFFIX,dynipv6.de,REJECT
DOMAIN-SUFFIX,eth64.de,REJECT
DOMAIN-SUFFIX,home64.de,REJECT
DOMAIN-SUFFIX,iot64.de,REJECT
DOMAIN-SUFFIX,ip-ddns.com,REJECT
DOMAIN-SUFFIX,ipv64.de,REJECT
DOMAIN-SUFFIX,ipv64.net,REJECT
DOMAIN-SUFFIX,lan64.de,REJECT
DOMAIN-SUFFIX,line.pm,REJECT
DOMAIN-SUFFIX,myjino.ru,REJECT
DOMAIN-SUFFIX,nas64.de,REJECT
DOMAIN-SUFFIX,root64.de,REJECT
DOMAIN-SUFFIX,route64.de,REJECT
DOMAIN-SUFFIX,run.place,REJECT
DOMAIN-SUFFIX,srv64.de,REJECT
DOMAIN-SUFFIX,sslip.io,REJECT
DOMAIN-SUFFIX,swtest.ru,REJECT
DOMAIN-SUFFIX,tcp64.de,REJECT
DOMAIN-SUFFIX,udp64.de,REJECT
DOMAIN-SUFFIX,vpn64.de,REJECT
DOMAIN-SUFFIX,wan64.de,REJECT
DOMAIN-SUFFIX,work.gd,REJECT
