# Title: HaGeZi's LG webOS Tracker DNS Blocklist
# Description: Blocks LG webOS native broadband tracker that track your activity.
# Homepage: https://github.com/hagezi/dns-blocklists
# License: https://github.com/hagezi/dns-blocklists/blob/main/LICENSE
# Issues: https://github.com/hagezi/dns-blocklists/issues
# Expires: 1 day
# Last modified: 08 Aug 2025 23:12 UTC
# Version: 2025.0808.2312.17
# Syntax: Domains (without subdomains)
# Number of entries: 18
#

DOMAIN-SUFFIX,alphonso.tv,REJECT
DOMAIN-SUFFIX,us-ad-lgsmartad-com.aws-prd.net,REJECT
DOMAIN-SUFFIX,us-info-lgsmartad-com.aws-prd.net,REJECT
DOMAIN-SUFFIX,eic-ngfts.lge.com.edgekey.net,REJECT
DOMAIN-SUFFIX,qt2-ngfts.lge.com.edgekey.net,REJECT
DOMAIN-SUFFIX,lgads.tv,REJECT
DOMAIN-SUFFIX,eic-ngfts.lge.com,REJECT
DOMAIN-SUFFIX,qt2-ngfts.lge.com,REJECT
DOMAIN-SUFFIX,ad.lgsmartad.com,REJECT
DOMAIN-SUFFIX,us.lgsmartad.com,REJECT
DOMAIN-SUFFIX,aic.ads.lgtvcommon.com,REJECT
DOMAIN-SUFFIX,eic.ads.lgtvcommon.com,REJECT
DOMAIN-SUFFIX,cdpbeacon.lgtvcommon.com,REJECT
DOMAIN-SUFFIX,homeprv.lgtvcommon.com,REJECT
DOMAIN-SUFFIX,nudge.lgtvcommon.com,REJECT
DOMAIN-SUFFIX,rdl.lgtvcommon.com,REJECT
DOMAIN-SUFFIX,wiseconfig.lgtvcommon.com,REJECT
DOMAIN-SUFFIX,h4g3z1-native.lgwebos.web.app,REJECT
